set_property PACKAGE_PIN R15 [get_ports {Data_in[3]}]
set_property PACKAGE_PIN M13 [get_ports {Data_in[2]}]
set_property PACKAGE_PIN L16 [get_ports {Data_in[1]}]
set_property PACKAGE_PIN J15 [get_ports {Data_in[0]}]
set_property PACKAGE_PIN T10 [get_ports {Seven_seg_data[6]}]
set_property PACKAGE_PIN R10 [get_ports {Seven_seg_data[5]}]
set_property PACKAGE_PIN K16 [get_ports {Seven_seg_data[4]}]
set_property PACKAGE_PIN K13 [get_ports {Seven_seg_data[3]}]
set_property PACKAGE_PIN P15 [get_ports {Seven_seg_data[2]}]
set_property PACKAGE_PIN T11 [get_ports {Seven_seg_data[1]}]
set_property PACKAGE_PIN L18 [get_ports {Seven_seg_data[0]}]
set_property PACKAGE_PIN J17 [get_ports AN0]
set_property PACKAGE_PIN H15 [get_ports DP]
set_property PACKAGE_PIN V11 [get_ports enable]

set_property IOSTANDARD LVCMOS33 [get_ports {Data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Seven_seg_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports DP]
set_property IOSTANDARD LVCMOS33 [get_ports AN0]


